Add userSchema and usersModel
cc-team-octoo/auth_service pull request #3
Opened 2019-12-07 11:40 UTC by MiroslawBiedrowski

2019-12-08 14:10 UTC, Aimekram requested changes

2019-12-08 14:10 UTC, Aimekram commented on src/app.js
> +const Users = mongoose.model("Users", userSchema);
Mosh mówił, że powinno być w liczbie pojedynczej tutaj, więc proponuję 
`const User = mongoose.model("User", userSchema);`

2019-12-08 14:10 UTC, Aimekram commented on src/app.js
> +const users = new Users({
Tu też powinna być liczba pojedyncza ;)
`const user = new User`

2019-12-08 19:30 UTC, Aimekram commented on src/app.js
> +  mail: String,
proponuję ustawić żeby email musiał być unikatowy
`email: {
type: String,
unique: true 
}`

2019-12-09 15:07 UTC, Aimekram approved these changes

2019-12-12 12:41 UTC, btomc approved these changes

2019-12-12 17:14 UTC, merged